blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (
    PostListView,
    PostDetailView,
    PostUpdateView,
    PostDeleteView,
    PostCreateView,
    ContactsView,
)


app_name = BlogConfig.name

urlpatterns = [
    path("post/", PostListView.as_view(), name="post_list"),
    path("post/contacts/", ContactsView.as_view(), name="contacts"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("post/create/", PostCreateView.as_view(), name="post_create"),
    path("post/<int:pk>/update/", PostUpdateView.as_view(), name="post_update"),
    path("post/<int:pk>/delete/", PostDeleteView.as_view(), name="post_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(
        max_length=150, verbose_name="Название", help_text="Введите название продукта"
    )
    text = models.TextField(
        verbose_name="Текст поста",
        blank=True,
        null=True,
        help_text="Введите текст поста",
    )
    image = models.ImageField(
        upload_to="images/",
        verbose_name="Изображение",
        blank=True,
        null=True,
        help_text="Загрузите фотографию к посту",
    )
    publication_sign = models.BooleanField(
        default=False, verbose_name="Признак публикации"
    )
    view_counter = models.PositiveIntegerField(
        verbose_name="Счетчик просмотров",
        default=0,
        help_text="Укажите кол-во просмотров",
    )
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания")

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "пост"
        verbose_name_plural = "посты"
        ordering = ["title"]

blog/forms.py
from django import forms
from .models import Post
from django.core.exceptions import ValidationError


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "publication_sign", "image", "text"]

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)

        # Настройка атрибутов виджета для поля 'first_name'
        self.fields["title"].widget.attrs.update({
            "class": "form-control",  # Добавление CSS-класса для стилизации поля
            "placeholder": 'Введите наименование поста'  # Текст подсказки внутри поля
        })

        # Настройка атрибутов виджета для поля 'last_name'
        self.fields["text"].widget.attrs.update({
            "class": "form-control",  # Добавление CSS-класса для стилизации поля
            "placeholder": 'Введите описание текст'  # Текст подсказки внутри поля
        })

        # Настройка атрибутов виджета для поля 'year'
        self.fields["image"].widget.attrs.update({
            "class": "form-control",  # Добавление CSS-класса для стилизации поля
            "placeholder": 'Укажите изображение поста'
        })

        # Настройка атрибутов виджета для поля 'email'
        self.fields["publication_sign"].widget.attrs.update({
            "class": "form-control"
        })

    def clean_title(self):
        title = self.cleaned_data.get("title")
        if Post.objects.filter(title=title).exists():
            raise ValidationError(
                "Пост с таким наименование уже есть."
            )
        return title

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpRequest
from .models import Post
from .forms import PostForm
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)


class ContactsView(TemplateView):
    template_name = "blog/contacts.html"

    def contacts(self, request, *args, **kwargs):
        """Обрабатываем форму и возвращаем ответ"""
        if self.request.method == "POST":
            name = request.POST.get("name")
            phone = request.POST.get("phone")
            message = request.POST.get("message")
            return HttpResponse(
                f"Спасибо, {name}, за Ваше сообщение! Наши специалисты скоро свяжутся с Вами по номеру телефона {phone}!"
            )
        return render(request, "contacts.html")


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(publication_sign=True)


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_counter += 1
        self.object.save()
        return self.object


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    # fields = ("title", "text", "image", "publication_sign")
    success_url = reverse_lazy("blog:post_list")


class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    # fields = ("title", "text", "image", "publication_sign")
    success_url = reverse_lazy("blog:post_list")

    def get_success_url(self):
        return reverse_lazy("blog:post_detail", kwargs={"pk": self.object.pk})


class PostDeleteView(DeleteView):
    model = Post
    fields = ("title", "text", "image", "publication_sign")
    success_url = reverse_lazy("blog:post_list")

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>БЛОГ</title>
    {% block title %}{% endblock %}
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <!-- Подключите статичеcкие файлы со стилями Bootstrap -->

</head>
<body>
{% include 'blog/includes/inc_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">БЛОГ</h1>
     <div class="btn-group">
         <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:post_create' %}" role="button">Создать</a>
     </div>
    <p class="lead">Самые интересные статьи здесь!</p>
</div>
{% block content %}{% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Блог
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Наши магазины</a></li>
                    <li><a class="text-muted" href="#">Написать нам в соцсетях</a></li>
                    <li><a class="text-muted" href="#">Работа у нас</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'blog:post_list' %}">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'blog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
      <title>БЛОГ</title>
    {% endblock %}
    <link href="/static/css/bootstrap.min.css" rel="stylesheet"/>
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">ПОСТЫ</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:post_list' %}">СПИСОК ПОСТОВ</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'blog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
</body>
</html>

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% block title %}
  <title>Удаление поста</title>
{% endblock %}


{% block content %}

<div class="container mt-5">
        <h1 class="mb-4">Удалить пост</h1>
        <p>Вы уверены, что хотите удалить "{{ object.title }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'blog:post_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% block title %}
  <title>Информация о посте</title>
{% endblock %}

{% block content %}

<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
        <div class="col">
          <div class="card shadow-sm">
              <div class="card-header">
                  <h4 class="my-0 font-weight-normal text-center">{{ object.title }}</h4>
              </div>
              <img src="{{ post.image | media_filter }}" width="100%" height="250">
              <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ object.text }}</h1>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>- Пост: {{ object.publication_sign }}</li>
                    <li>- Описание: {{ object.text }}</li>
                </ul>
              <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:post_update' post.pk %}" role="button">Редактировать</a>
                    </div>
                    <div class="btn-group">
                        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:post_delete' post.pk %}" role="button">Удалить</a>
                    </div>
                    <div class="btn-group">
                        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:post_list' %}" role="button">Назад</a>
                    </div>

              </div>
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% block title %}
  <title>Добавление поста</title>
{% endblock %}

{% block content %}

<div class="container mt-5">
        <h1 class="mb-4">
            {% if post %}
            Форма изменения поста
            {% else %}
            Форма создания поста
            {% endif %}
        </h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">
                {% if post %}
                Сохранить
                {% else %}
                Создать
                {% endif %}
            </button>
            <a href="{% url 'blog:post_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% block title %}Главная страница блога{% endblock %}

{% block content %}

<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
        {% for post in object_list %}
        <div class="col">
          <div class="card shadow-sm">
              <div class="card-header">
                  <h4 class="my-0 font-weight-normal text-center">{{ post.title }}</h4>
              </div>
              <img src="{{ post.image | media_filter }}" width="100%" height="250">

              <div class="card-body">

                <ul class="list-unstyled mt-3 mb-4 text-start m-3">

                    <li>- Текст поста: {{ post.text | truncatechars:100 }}</li>
                    <li>- Количество просмотров: {{ post.view_counter }}</li>
                </ul>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:post_detail' post.pk %}" role="button">Подробнее</a>
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:post_update' post.pk %}" role="button">Изменить</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}