blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (
    PostListView,
    PostDetailView,
    PostUpdateView,
    PostDeleteView,
    PostCreateView,
    ContactsView,
)


app_name = BlogConfig.name

urlpatterns = [
    path("post/", PostListView.as_view(), name="post_list"),
    path("post/contacts/", ContactsView.as_view(), name="contacts"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("post/create/", PostCreateView.as_view(), name="post_create"),
    path("post/<int:pk>/update/", PostUpdateView.as_view(), name="post_update"),
    path("post/<int:pk>/delete/", PostDeleteView.as_view(), name="post_delete"),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from catalog.apps import CatalogConfig
from catalog.views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ContactsView,
    UnpublishProductView,
    CategoryProductView,
    CategoryListView
)


app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="product_list"),
    path("contacts/", ContactsView.as_view(), name="contacts"),
    path("product/<int:pk>/", cache_page(60)(ProductDetailView.as_view()), name="product_detail"),
    path("product/create", ProductCreateView.as_view(), name="product_create"),
    path("product/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),
    path("products/<int:pk>/unpublish/", UnpublishProductView.as_view(), name="unpublish_product"),
    path("categories_list/", CategoryListView.as_view(), name="category_list"),
    path("categories/<int:pk>/", CategoryProductView.as_view(), name="category_products"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import CustomUser


class Category(models.Model):
    title = models.CharField(
        max_length=150, verbose_name="Название", help_text="Введите название категории"
    )
    description = models.TextField(
        verbose_name="Описание",
        blank=True,
        null=True,
        help_text="Введите описание категории",
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ["title"]


class Product(models.Model):
    title = models.CharField(
        max_length=150, verbose_name="Название", help_text="Введите название продукта"
    )
    description = models.TextField(
        verbose_name="Описание",
        blank=True,
        null=True,
        help_text="Введите описание продукта",
    )
    image = models.ImageField(
        upload_to="images/",
        verbose_name="Изображение",
        blank=True,
        null=True,
        help_text="Загрузите фотографию продукта",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="products",
        verbose_name="Категория",
    )
    publish_status = models.BooleanField(
        default=False,
        help_text="Укажите статус публикации продукта",
        verbose_name="Статус публикации",
    )
    owner = models.ForeignKey(
        CustomUser,
        verbose_name="Владелец",
        on_delete=models.CASCADE,
        related_name="products",
        null=True,
        blank=True,
    )
    price = models.FloatField(verbose_name="Цена", help_text="Введите цену продукта")
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateField(auto_now=True, verbose_name="Дата изменения")
    view_counter = models.PositiveIntegerField(
        verbose_name="Счетчик просмотров",
        default=0,
        help_text="Укажите кол-во просмотров",
    )

    def __str__(self):
        return f"{self.title} {self.price}"

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        ordering = ["title"]
        permissions = [
            ("can_unpublish_product", "can unpublish product"),
        ]

catalog/forms.py
from django import forms
from .models import Product
from django.core.exceptions import ValidationError

forbidden_words = [
    "казино",
    "криптовалюта",
    "крипта",
    "биржа",
    "дешево",
    "бесплатно",
    "обман",
    "полиция",
    "радар",
]


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["title", "description", "image", "category", "price"]

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

        # Настройка атрибутов виджета для поля 'first_name'
        self.fields["title"].widget.attrs.update({
            "class": "form-control",  # Добавление CSS-класса для стилизации поля
            "placeholder": 'Введите наименование продукта'  # Текст подсказки внутри поля
        })

        # Настройка атрибутов виджета для поля 'last_name'
        self.fields["description"].widget.attrs.update({
            "class": "form-control",  # Добавление CSS-класса для стилизации поля
            "placeholder": 'Введите описание продукта'  # Текст подсказки внутри поля
        })

        # Настройка атрибутов виджета для поля 'year'
        self.fields["image"].widget.attrs.update({
            "class": "form-control",  # Добавление CSS-класса для стилизации поля
            "placeholder": 'Укажите изображение продукта'
        })

        # Настройка атрибутов виджета для поля 'email'
        self.fields["category"].widget.attrs.update({
            "class": "form-control",
            "placeholder": 'Укажите категорию продукта'
        })

        self.fields["price"].widget.attrs.update({
            "class": "form-control",
            "placeholder": 'Укажите цену продукта'
        })

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price < 0:
            raise ValidationError("Цена не может быть отрицательной")
        return price

    def clean_title(self):
        title = self.cleaned_data.get("title")
        if any(word in title.lower() for word in forbidden_words):
            raise ValidationError("В наименовании есть запрещенные слова.")
        elif Product.objects.filter(title=title).exists():
            raise ValidationError("Продукт с таким наименованием уже есть.")
        return title

    def clean_description(self):
        description = self.cleaned_data.get("description")
        if any(word in description.lower() for word in forbidden_words):
            raise ValidationError("В наименовании есть запрещенные слова.")
        return description

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpRequest
from .models import Product, Category
from django.http import HttpResponseForbidden
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import ProductForm
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from .service import category_products, get_product_list
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
    View,
)


class CategoryListView(ListView):
    """Контроллер отображения списка категорий продуктов."""

    model = Category
    template_name = "catalog/category_list.html"


class ContactsView(TemplateView):
    template_name = "catalog/contacts.html"

    def contacts(self, request):
        """Обрабатываем форму и возвращаем ответ"""
        if self.request.method == "POST":
            name = request.POST.get("name")
            phone = request.POST.get("phone")
            message = request.POST.get("message")
            return HttpResponse(
                f"Спасибо, {name}, за Ваше сообщение! Наши специалисты скоро свяжутся с Вами по номеру телефона {phone}!"
            )
        return render(request, "contacts.html")


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = "catalog/product_list.html"

    def get_queryset(self):
        return get_product_list()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["published_products"] = Product.objects.filter(publish_status=True)
        return context


@method_decorator(cache_page(60 * 1), name='dispatch')
class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_counter += 1
        self.object.save()
        return self.object


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")
    login_url = reverse_lazy("users:login")

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        if self.request.user != product.owner:
            return HttpResponseForbidden("У вас не достаточно прав.")

    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")
    login_url = reverse_lazy("users:login")

    def get_success_url(self):
        return reverse_lazy("catalog:product_detail", kwargs={"pk": self.object.pk})



class ProductDeleteView(LoginRequiredMixin, DeleteView):
    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        if (
            not self.request.user.has_perm("delete_product")
            or self.request.user != product.owner
        ):
            return HttpResponseForbidden("У вас не достаточно прав.")

    model = Product
    template_name = "catalog/product_confirm_delete.html"
    success_url = reverse_lazy("catalog:product_list")


class UnpublishProductView(LoginRequiredMixin, View):
    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        if not request.user.has_perm("can_unpublish_product"):
            return HttpResponseForbidden("У вас не достаточно прав.")

        product.publish_status = False
        product.save()
        return redirect("catalog:product_list")


class CategoryProductView(LoginRequiredMixin, ListView):
    """Контроллер отображения всех продуктов в отдельной категории."""

    template_name = "catalog/category_product.html"
    context_object_name = "products"
    login_url = reverse_lazy("users:login")

    def get_queryset(self):
        print(self.kwargs)
        pk = self.kwargs.get("pk")
        print(pk)
        return category_products(pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["products"] = self.get_queryset()
        return context

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Продукты</title>
    {% block title %}{% endblock %}
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <!-- Подключите статичеcкие файлы со стилями Bootstrap -->

</head>
<body>
{% include 'catalog/includes/inc_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">ФЕРМЕРСКИЕ ПРОДУКТЫ</h1>
     <div class="btn-group">
         <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:product_create' %}" role="button">Создать</a>
     </div>
    <p class="lead">доставка за 2 часа</p>
</div>
{% block content %}{% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Продуктовый
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Наши магазины</a></li>
                    <li><a class="text-muted" href="#">Написать нам в соцсетях</a></li>
                    <li><a class="text-muted" href="#">Работа у нас</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base_template.html' %}
{% load my_tags %}
{% block title %}Список категорий продуктов{% endblock %}

{% block content %}

<div class="container">
    <div class="container mt-3">
            <h1 class="my-0 font-weight-normal text-center">Категории продуктов</h1>
    </div>
        {% for category in object_list %}


        <div class="container mt-3">
            <h4 class="my-0 font-weight-normal">Категория продуктов "{{category}}"</h4>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:category_products' category.pk %}" role="button">Продукты категории</a>
                </div>
              </div>
        </div>

        {% endfor %}

{% endblock %}

catalog/templates/catalog/category_product.html
{% extends 'catalog/base_template.html' %}
{% load my_tags %}
{% block title %}Продукты категории{% endblock %}

{% block content %}

<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
        {% for product in products %}
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal text-center">{{ product.title }}</h4>
                </div>
                <img height="250" src="{{ product.image | media_filter }}" width="100%">

                <div class="card-body">

                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Категория продукта: {{ product.category }}</li>
                        <li>- Описание продукта: {{ product.description | truncatechars:100 }}</li>
                        <li>- Количество просмотров: {{ product.view_counter }}</li>
                    </ul>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-lg btn-block btn-outline-primary"
                               href="{% url 'catalog:product_detail' product.pk %}" role="button">Подробнее</a>
                            {% if perms.products.delete_product or self.request.user == product.owner%}
                            <a class="btn btn-lg btn-block btn-outline-primary"
                               href="{% url 'catalog:product_update' product.pk %}" role="button">Изменить</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
      <title>Продукты</title>
    {% endblock %}
    <link href="/static/css/bootstrap.min.css" rel="stylesheet"/>
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">ФЕРМЕРСКИЕ ПРОДУКТЫ</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
</body>
</html>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block title %}
  <title>Удаление продукта</title>
{% endblock %}


{% block content %}

<div class="container mt-5">
        <h1 class="mb-4">Удалить продукт</h1>
        <p>Вы уверены, что хотите удалить "{{ object.title }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'catalog:product_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block title %}
  <title>Продукты</title>
{% endblock %}

{% block content %}

<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
        <div class="col">
          <div class="card shadow-sm">
              <div class="card-header">
                  <h4 class="my-0 font-weight-normal text-center">{{ object.title }}</h4>
              </div>
              <img src="{{ product.image | media_filter }}" width="100%" height="250">
              <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ object.price }} рублей</h1>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>- Категория продукта: {{ object.category }}</li>
                    <li>- Описание продукта: {{ object.description }}</li>
                </ul>
              <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a class="btn btn-lg btn-block btn-outline-primary" href="#" role="button">Посмотреть</a>
                    </div>
                  {% if perms.products.delete_product or self.request.user == product.owner%}
                    <div class="btn-group">
                        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:product_delete' product.pk %}" role="button">Удалить</a>
                    </div>
                  {% endif %}
                    <div class="btn-group">
                        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:product_list' %}" role="button">Назад</a>
                    </div>

              </div>
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block title %}
  <title>Добавление продукта</title>
{% endblock %}

{% block content %}

<div class="container mt-5">
        <h1 class="mb-4">
            {% if product %}
            Форма изменения продукта
            {% else %}
            Форма создания продукта
            {% endif %}
        </h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">
                {% if product %}
                Сохранить
                {% else %}
                Создать
                {% endif %}
            </button>
            <a href="{% url 'catalog:product_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block title %}
  <title>Главная страница магазина</title>
{% endblock %}

{% block 'catalog/includes/inc_menu.html' %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
         {% for product in published_products %}
        <div class="col">
          <div class="card shadow-sm">
              <div class="card-header">
                  <h4 class="my-0 font-weight-normal text-center">{{ product.title }}</h4>
              </div>
              <img src="{{ product.image | media_filter }}" width="100%" height="250">

              <div class="card-body">

                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>- Категория продукта: {{ product.category }}</li>
                    <li>- Описание продукта: {{ product.description | truncatechars:100 }}</li>
                    <li>- Количество просмотров: {{ product.view_counter }}</li>
                </ul>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:product_detail' product.pk %}" role="button">Подробнее</a>
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:product_update' product.pk %}" role="button">Редактировать</a>
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:product_delete' product.pk %}" role="button">Удалить</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}